config:
  fieldsWhitelist:
    - 'login'
    - 'id'
    - 'avatar_url'
    - 'html_url'
    - 'name'
    - 'company'
    - 'blog'
    - 'location'
    - 'bio'
  extractEmailDomain: true
  keepExcludedUsers: false
  keepedRepositories:
    - "PrestaShop-backward_compatibility"
    - "standard_coding_hook"
    - "translationsenglish"
    - "PrestaShop-norm-validator"
    - "translatools"
    - "module-generator"
    - "backwardcompatibility"
    - "pscleaner"
    - "themeinstallator"
    - "prestafraud"
    - "PrestaShopAutomationFramework"
    - "pssupport"
    - "securitypatch"
    - "StarterTheme"
    - "solrsearch"
    - "community-theme-16"
    - "demonstration"
    - "ps_legalcompliance"
    - "InstallUnpacker"
    - "CldrCleaner"
    - "PSFunctionalTests"
    - "ps_emailgenerator"
    - "prestonbot"
    - "ps_rssfeed"
    - "ps_advertising"
    - "ps_productinfo"
    - "ps_carriercomparison"
    - "ps_feeder"
    - "ps_reminder"
    - "travis-status-board"
    - "core-weekly-generator"
    - "PythonTests"
    - "GitHubMonitoring"
    - "ps_livetranslation"
    - "firebaseauthenticator"
    - "prestafony-project"
    - "ps_buybuttonlite"
    - "module-companion"
    - "composer-script-handler"
    - "example_module_mailtheme"
    - "ps_healthcheck"
    - "presthubot-ui"
    - "user-documentation-landing"
  exclusions:
    - dependabot
    - dependabot[bot]
    - dependabot-preview
    - dependabot-preview[bot]
    - devops-prestashop
    - gitbook-bot
    - ps-jarvis
    - github-actions
    - github-actions[bot]
    - prestonBot
