name: Lint
on: 
    push:
        branches:
            - master
    pull_request:

jobs:
  jsonlint:
    name: JSON Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      -   name: Install jq
          run: sudo apt-get install -y jq

      -   name: Validate JSON
          run: jq -e . <<<$(cat var/data/companies.json)
